### PR TITLE
[Hmk/url decryption v1] Fixed static file serving issues

### PR DESCRIPTION
**Pull request by huzaifamk**
## Description
Fixed the issue of profile picture not appearing and static file was not being served properly.

## A test suite of simple manual tests to ensure functionality is preserved.

SECTION 1: WEVE GOT POEMS (http://localhost:5173/)
[ ] Log in with 'tester' / '1234'
[ ] Log in anonymously with Layer8
[ ] Clicking "Get Next Poem" loads different poem correctly x 3
[ ] Clicking "Logout" takes you to the login screen
[ ] Clicking "Register" takes you to the registration page
[ ] Registering with a username, password, and profile image is successful
[ ] Logging in with the new username / password succeeds
[ ] Logging in with Layer8 opens the pop-up
[ ] Logging in with the "tester" & "12341234" works
[ ] User chooses to share their new "Username" & "Country" from the Layer8 Resource Server
[ ] Clicking "Get Next Poem" loads different poem correctly x 3
[ ] Clicking "Logout" takes you to the login page

SECTION 2: IMSHARER (http://localhost:5174/)
[ ] Main page loads
[ ] Upload of image works
[ ] Reload leads to instant reload (demonstrating proper caching)
[ ] Clicking the newly loaded image shows it in a light boxLog in using tester and 12341234 should succeed

### CODE REVIEW

**Review by DeeStarks — COMMENTED** [review]
The code looks good, but do you mind describing the thought process behind the changes, and reason for change? It'll help to understand the code much better

**Comment by huzaifamk** [comment]
> The code looks good, but do you mind describing the thought process behind the changes, how it fixes the issue, and things like that? It'll help to understand the code much better
> 
> You could update the PR description
> 
> Also, I'm not sure if the right `utils` package was imported in `middleware.go` image
> 
> I think we need to do a cleanup and have only one `utils`

This is coming from here: https://github.com/globe-and-citizen/layer8-utils/commit/aafc0b438156839e7c6f9486db4933e0270b5722

A simple `go get github.com/globe-and-citizen/layer8-utils` should solve this problem, I think this is occuring because on your local machine, you are using old version of layer8_utils, you need to upgrade dependencies.

**Review by DeeStarks — COMMENTED** [review]
LGTM. I'm not explicitly approving because I haven't been able to get it to work. I've left a comment on the interceptor's PR about details

**Review by DeeStarks — APPROVED** [review]
Looks good. However, I think we should clear the prints so they are not being logged on SP's stdout

**Pull request merged**
